export const customError = {
  ownableUnauthorizedAccount: 'OwnableUnauthorizedAccount',
  newOwnerNotZeroAddress: 'NewOwnerNotZeroAddress',
  baseTokenNotZeroAddress: 'BaseTokenNotZeroAddress',
  boostTokenNotZeroAddress: 'BoostTokenNotZeroAddress',
  verifierNotZeroAddress: 'VerifierNotZeroAddress',
  goalNotZero: 'GoalNotZero',
  startDateMustBeGreaterThanCurrentTime: 'StartDateMustBeGreaterThanCurrentTime',
  closeDateMustBeGreaterThanCurrentTime: 'CloseDateMustBeGreaterThanCurrentTime',
  closeDateMustBeGreaterThanStartDate: 'CloseDateMustBeGreaterThanStartDate',
  timeoutBlocker: 'TimeoutBlocker',
  amountNotZero: 'AmountNotZero',
  invalidSignature: 'InvalidSignature',
  usedTransactionId: 'UsedTransactionId',
  userMustAllowToUseFunds: 'UserMustAllowToUseFunds',
  userMustHaveFunds: 'UserMustHaveFunds',
  invalidNonce: 'InvalidNonce',
  tooEarly: 'TooEarly',
  tooLate: 'TooLate',
  goalUnreached: 'GoalUnreached',
  allUsersProcessed: 'AllUsersProcessed',
};
