export const customError = {
  ownableUnauthorizedAccount: 'OwnableUnauthorizedAccount',
  newOwnerNotZeroAddress: 'NewOwnerNotZeroAddress',
  baseTokenNotZeroAddress: 'BaseTokenNotZeroAddress',
  boostTokenNotZeroAddress: 'BoostTokenNotZeroAddress',
  boostExchangeRateNotZero: 'BoostExchangeRateNotZero',
  depositVerifierNotZeroAddress: 'DepositVerifierNotZeroAddress',
  goalNotZero: 'GoalNotZero',
  startDateMustBeGreaterThanCurrentTime: 'StartDateMustBeGreaterThanCurrentTime',
  closeDateMustBeGreaterThanCurrentTime: 'CloseDateMustBeGreaterThanCurrentTime',
  closeDateMustBeGreaterThanStartDate: 'CloseDateMustBeGreaterThanStartDate',
  timeoutBlocker: 'TimeoutBlocker',
  baseAmountNotZero: 'BaseAmountNotZero',
  invalidSignature: 'InvalidSignature',
  usedTransactionId: 'UsedTransactionId',
  userMustAllowToUseFunds: 'UserMustAllowToUseFunds',
  userMustHaveFunds: 'UserMustHaveFunds',
  userHasBoostedDeposit: 'UserHasBoostedDeposit',
  invalidNonce: 'InvalidNonce',
  tooEarly: 'TooEarly',
  tooLate: 'TooLate',
  unreachedGoal: 'UnreachedGoal',
  allUsersProcessed: 'AllUsersProcessed',
};
